replicaCount: 2
namespace: proj-ns

flaskApp:
  name: flask-app
  image: davidnoy/dev_sec_ops_final
  tag: dev-app-0.0.4-12
  port: 59000

pythonServer:
  name: python-server
  image: davidnoy/dev_sec_ops_final
  tag: dev-server-0.0.1-12
  port: 8000
